version: "3.8"

services:
  db:
    image: postgres:12.4
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - it_profi/.env
  django:
    build:
      context: ./it_profi
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: always
    env_file:
      - it_profi/.env
    volumes:
      - static:/code/static
      - media:/code/media
      - nginx_conf:/code/nginx.conf
    entrypoint: /code/entrypoint.sh
  nginx:
    image: nginx:1.19.0-alpine
    ports:
      - "80:80"
    volumes:
      - static:/code/static
      - media:/code/media
      - nginx_conf:/etc/nginx/conf.d/
    depends_on:
      - django
    restart: always

volumes:
  postgres_data:
  static:
  media:
  nginx_conf:
