version: "3.8"

services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: it12345
      POSTGRES_DB: django_db
    ports:
      - "5432:5432"
  django-app:
    build:
      context: ./it_profi
    container_name: django_project
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    environment:
      DEBUG: 'False'
      DB_NAME: 'django_db'
      DB_USER: 'admin'
      DB_PASSWORD: 'it12345'
      DB_HOST: 'localhost'
      DB_PORT: 5432
    volumes:
      - static_volume:/app/static
  nginx:
    image: nginx:latest
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/static
    ports:
      - "80:80"
    depends_on:
      - django-app

volumes:
  static_volume: